### PR TITLE
Make make content section slugs nicer

### PR DESCRIPTION
**Pull request by robyoung**
Strip ampersands and question marks from section names an trim them when converting them into slugs. Question marks in slugs make my day really bad.

### CODE REVIEW

**Comment by TheDoubleK** [comment]
The change looks good, but I just wonder if it might break some tests elsewhere?  It would be good to run both the SSP functional tests and the supplier app unit tests against this new version before merging.

**Comment by robyoung** [comment]
Good call, I will look into that now.

**Comment by robyoung** [comment]
Phew! Finally. After battling with my local environment I've managed to test this and it :sparkles: passes functional tests :sparkles:.

**Comment by TheDoubleK** [comment]
Nice work :+1:

**Pull request merged**
