### PR TITLE
Exclude external routes from list_routes output

### PR DESCRIPTION
**Pull request by lfdebrux**
This output makes more sense to me, feel free to reject if you disagree.

### CODE REVIEW

**Comment by lfdebrux** [comment]
@risicle I'm not sure what you mean? I assumed this was just a command line tool useful for documentation purposes (which is what I was using it for)

**Comment by katstevens** [comment]
🤔 I think it's useful to know which external routes are available for the app? Can we list them separately?

**Comment by katstevens** [comment]
Cool 👍 I'd forgotten that we even had this method available!

**Comment by risicle** [comment]
Sure yeah, I've just never seen this used yet.

**Pull request merged**
